version: "3.8"

services:
  database:
    container_name: database
    build:
      dockerfile: database.Dockerfile
    ports:
      - 27017:27017
    env_file:
      - ./.db.env
    volumes:
      - ./mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - db_data:/data/db
    restart: always

  api:
    container_name: api
    build:
      dockerfile: api.Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - database
    restart: always

volumes:
  db_data:
